# Generated by Django 5.2.1 on 2025-05-11 02:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Booking number must be alphanumeric', regex='^[A-Za-z0-9-]+$')])),
                ('loading_port', models.CharField(max_length=100)),
                ('discharge_port', models.CharField(max_length=100)),
                ('ship_arrival_date', models.DateTimeField()),
                ('ship_departure_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='VIN must be a valid 17-character Vehicle Identification Number', regex='^[A-HJ-NPR-Z0-9]{17}$')], verbose_name='VIN')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='logistics.booking')),
            ],
        ),
    ]
