from django.conf import settings

# Default settings
DEFAULTS = {
    'OLD_VEHICLES_DAYS': 180,  # Days to consider vehicles "old" (6 months)
    'VIN_VALIDATOR_REGEX': r'^[A-HJ-NPR-Z0-9]{17}$',
    'BOOKING_NUMBER_REGEX': r'^[A-Za-z0-9-]+$',
    'DEFAULT_VEHICLE_WEIGHT': 1500.00,
    'DEFAULT_VEHICLE_MAKE': 'Default Make',
    'DEFAULT_VEHICLE_MODEL': 'Default Model',
}

# Get user settings
USER_SETTINGS = getattr(settings, 'LOGISTICS_SETTINGS', {})

# Combine defaults with user settings
LOGISTICS_SETTINGS = DEFAULTS.copy()
LOGISTICS_SETTINGS.update(USER_SETTINGS)

# Export settings as variables for easy access
OLD_VEHICLES_DAYS = LOGISTICS_SETTINGS['OLD_VEHICLES_DAYS']
VIN_VALIDATOR_REGEX = LOGISTICS_SETTINGS['VIN_VALIDATOR_REGEX']
BOOKING_NUMBER_REGEX = LOGISTICS_SETTINGS['BOOKING_NUMBER_REGEX']
DEFAULT_VEHICLE_WEIGHT = LOGISTICS_SETTINGS['DEFAULT_VEHICLE_WEIGHT']
DEFAULT_VEHICLE_MAKE = LOGISTICS_SETTINGS['DEFAULT_VEHICLE_MAKE']
DEFAULT_VEHICLE_MODEL = LOGISTICS_SETTINGS['DEFAULT_VEHICLE_MODEL']

